wallpaper {
#Leave this blank to autodetect monitors (can make the wallpaper appear with a little delay
  monitor =
#If you want to change the wallpaper just put a different image in the same folder with the same name
  path = ~/.config/hypr/wallpaper.jpg
}

splash = false
